language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install .
  - pip install -r dev-requirements.txt
  - pip install coveralls
# command to run tests
script:
  - pylint capablanca
  - pep8 capablanca/*.py -v
  - py.test --cov=.
after_sucess:
  - coveralls
